### ISSUE TITLE
Single error message Unhandled promise rejection. / Connection is closed

### ISSUE THREAD

**Issue by Grothesk242** [peterbaumert/ioBroker.vodafone-speedtest#30]
Seems like hickup on vodafone's site. 
This error message only occured once, maybe it can be catched somehow and be replaced a message in the log like
'vodafone Speedtest is not responding, trying again later' 

```
2021-05-23 07:53:31.389  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-23 07:53:31.396  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) unhandled promise rejection: Connection is closed.
2021-05-23 07:53:31.404  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:183:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:150:20)
    at Object.onceWrapper (node:events:472:26)
    at Socket.emit (node:events:365:28)
    at Socket.emit (node:domain:470:12)
    at TCP.<anonymous> (node:net:661:12)
2021-05-23 07:53:31.405  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Connection is closed.
2021-05-23 07:53:31.418  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-23 07:53:31.418  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) unhandled promise rejection: Connection is closed.
2021-05-23 07:53:31.419  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Error: Connection is closed.
    at close (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:183:25)
    at Socket.<anonymous> (/opt/iobroker/node_modules/ioredis/built/redis/event_handler.js:150:20)
    at Object.onceWrapper (node:events:472:26)
    at Socket.emit (node:events:365:28)
    at Socket.emit (node:domain:470:12)
    at TCP.<anonymous> (node:net:661:12)
2021-05-23 07:53:31.420  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Connection is closed.
2021-05-23 07:53:31.424  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.425  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.426  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.426  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.427  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.428  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.428  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.429  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.429  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.430  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.430  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.431  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
2021-05-23 07:53:31.432  - ESC[31merrorESC[39m: vodafone-speedtest.0 (18668) Create state error = Error: Connection is closed.
```

**Comment by peterbaumert** [comment]
Looks more like a database issue to me to be honest. It fails on creating the state, cuz its not connected to db anymore.
